#!/bin/bash

BOOTLOADER_HEX=$(catkin_find --share rosserial_leonardo_cmake bootloader/Caterina-Leonardo.hex)
AVRDUDE_FLAGS="-p m32u4 -P usb -c avrispmkii -B5"

sudo avrdude $AVRDUDE_FLAGS -e
sudo avrdude $AVRDUDE_FLAGS -U lfuse:w:0xFC:m -U hfuse:w:0xD0:m -U efuse:w:0xC3:m 
sudo avrdude $AVRDUDE_FLAGS -B 1 -U flash:w:$BOOTLOADER_HEX
sudo avrdude $AVRDUDE_FLAGS -U lock:w:0x2F:m
