#!/bin/bash

HEX_FILE=$(catkin_find $1 $2)

if [[ ! "$NORESET" ]]; then
  rosrun rosserial_leonardo_cmake enter_bootloader /dev/arduino
  if [[ "$?" == "1" ]]; then
    echo "Automatic reset failed, please manually reset MCU."
    sleep 3
  fi
fi
avrdude -patmega32u4 -cavr109 -b57600 -P/dev/arduino -D -V -Uflash:w:${HEX_FILE}
